services:

  redis:
    image: redis:latest
    restart: always
    # Configure Redis as the lru-cache
    command: [ "redis-server", "--maxmemory", "500mb", "--maxmemory-policy", "allkeys-lru" ]
    expose:
      - 6379

  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  redis_cache:
    image: redis_cache
    build:
      context: ./redis_cache
    networks:
      - default

  prestart:
    build:
      context: first_service
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy
      redis_cache:
        condition: service_started
      external_apis:
        condition: service_started
    command: bash scripts/prestart.sh
    volumes:
      - ./first_service/app/alembic/versions:/app/app/alembic/versions
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}

  first_service:
    ports:
      - "8000:8000"
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy
      redis_cache:
        condition: service_started
      external_apis:
        condition: service_started
    volumes:
      - ./first_service/htmlcov:/app/htmlcov
      # For changing request's policy to services on flight
      - ./first_service/data_sources_config.json:/app/data_sources_config.json
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5

    build:
      context: ./first_service

  second_service:
    ports:
      - "8001:8001"
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy
      redis_cache:
        condition: service_started
      external_apis:
        condition: service_started
    volumes:
      - ./second_service/htmlcov:/app/htmlcov
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/api/v1/utils/health-check/" ]
      interval: 10s
      timeout: 5s
      retries: 5

    build:
      context: ./second_service
  
  external_apis:
    image: external_apis
    build:
      context: ./external_apis
    ports: 
      - "3629:3629"
    networks:
      - default


volumes:
  app-db-data: