#! /usr/bin/env bash

# Let the DB start
python app/backend_pre_start.py

# Function to check for pending migrations
check_for_migrations() {
    # Run alembic check command
    OUTPUT=$(alembic check 2>&1)

    if [ $? -ne 0 ]; then
        echo "Error during alembic check: $OUTPUT"
        return 2
    fi

    # Check the output for specific indicators of pending migrations
    if echo "$OUTPUT" | grep -q "FAILED"; then
        echo "There are pending migrations."
        return 0
    else
        echo "No pending migrations."
        return 1
    fi
}

# Function to generate a new migration
generate_migration() {
    # Run alembic revision --autogenerate
    OUTPUT=$(alembic revision --autogenerate -m "autogenerated_migration" 2>&1)

    if [ $? -eq 0 ]; then
        echo "Migration generated successfully."
    else
        echo "Failed to generate migration: $OUTPUT"
    fi
}

## Main script logic
#if check_for_migrations; then
#    generate_migration
#else
#    echo "No migration needed."
#fi

# Temp: uncomment when need to add fields or tables
#generate_migration
# Run migrations
alembic upgrade head
