[project]
name = "external-apis"
version = "0.1.0"
description = "A simple service to simulate external API responses"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.3",
    "uvicorn>=0.32.0",
]
