{
 "title": "DWH Order",
 "time": { "from": "2024-12-23T07:10:31.000Z", "to": "2024-12-23T18:10:31.000Z" },
 "panels": [
  {
   "title": "Итоговая сумма по заказам",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    snapshot_datetime, \r\n    SUM(total_coins) AS total_order_sum\r\nFROM \r\n    OrderStatisticsSnapshots\r\nGROUP BY \r\n    snapshot_datetime\r\nORDER BY \r\n    snapshot_datetime;\r\n"
    }
   ]
  },
  {
   "title": "Средняя итоговая цена заказа",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    snapshot_datetime, \r\n    avg_order_price \r\nFROM \r\n    OrderStatisticsSnapshots\r\nORDER BY \r\n    snapshot_datetime;\r\n"
    }
   ]
  },
  {
   "title": "Общая сумма бонусов",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    snapshot_datetime, \r\n    SUM(bonus_sum) AS total_bonus\r\nFROM \r\n    OrderStatisticsSnapshots\r\nGROUP BY \r\n    snapshot_datetime\r\nORDER BY \r\n    snapshot_datetime;\r\n"
    }
   ]
  },
  {
   "title": "Количество заказов со статусом `Active`",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    snapshot_datetime, \r\n    active_count \r\nFROM \r\n    orderstatisticssnapshots\r\nORDER BY \r\n    snapshot_datetime;\r\n"
    }
   ]
  },
  {
   "title": "Количество заказов со статусами `Cancelled` и `Done` (Дельта)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "WITH status_deltas AS (\r\n    SELECT \r\n        snapshot_datetime, \r\n        cancelled_count - LAG(cancelled_count) OVER (ORDER BY snapshot_datetime) AS cancelled_delta,\r\n        done_count - LAG(done_count) OVER (ORDER BY snapshot_datetime) AS done_delta\r\n    FROM \r\n        OrderStatisticsSnapshots\r\n)\r\nSELECT \r\n    snapshot_datetime, \r\n    COALESCE(cancelled_delta, 0) AS cancelled_delta, \r\n    COALESCE(done_delta, 0) AS done_delta\r\nFROM \r\n    status_deltas\r\nORDER BY \r\n    snapshot_datetime;\r\n"
    }
   ]
  }
 ]
}