{
 "title": "DWH",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Время принятия заказа по конкретному пользователю и по среднему (в секундах)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT executor_id,\r\n       acceptance_time,\r\n       AVG(acceptance_time) OVER () AS avg_acceptance_time_seconds\r\nFROM ExecutorStatistics;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Кол-во взятых заказов конкретным исполнителем",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT executor_id,\r\n       accepted_orders_count\r\nFROM ExecutorStatistics;\r\n"
    }
   ]
  },
  {
   "title": "Общая сумма бонусов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    snapshot_datetime, \r\n    SUM(bonus_sum) AS total_bonus\r\nFROM \r\n    OrderStatisticsSnapshots\r\nGROUP BY \r\n    snapshot_datetime\r\nORDER BY \r\n    snapshot_datetime;\r\n"
    }
   ]
  },
  {
   "title": "Итоговая сумма по заказам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    snapshot_datetime, \r\n    SUM(total_coins) AS total_order_sum\r\nFROM \r\n    OrderStatisticsSnapshots\r\nGROUP BY \r\n    snapshot_datetime\r\nORDER BY \r\n    snapshot_datetime;\r\n"
    }
   ]
  },
  {
   "title": "Кол-во заказов по статусам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    snapshot_datetime, \r\n    active_count \r\nFROM \r\n    OrderStatisticsSnapshots\r\nORDER BY \r\n    snapshot_datetime;\r\n"
    },
    {
     "rawSql": "WITH status_deltas AS (\r\n    SELECT \r\n        snapshot_datetime, \r\n        cancelled_count - LAG(cancelled_count) OVER (ORDER BY snapshot_datetime) AS cancelled_delta,\r\n        done_count - LAG(done_count) OVER (ORDER BY snapshot_datetime) AS done_delta\r\n    FROM \r\n        OrderStatisticsSnapshots\r\n)\r\nSELECT \r\n    snapshot_datetime, \r\n    COALESCE(cancelled_delta, 0) AS cancelled_delta, \r\n    COALESCE(done_delta, 0) AS done_delta\r\nFROM \r\n    status_deltas\r\nORDER BY \r\n    snapshot_datetime;\r\n"
    }
   ]
  },
  {
   "title": "Средняя итоговая цена заказа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    snapshot_datetime, \r\n    avg_order_price \r\nFROM \r\n    OrderStatisticsSnapshots\r\nORDER BY \r\n    snapshot_datetime;\r\n"
    }
   ]
  }
 ]
}