"""autogenerated_migration

Revision ID: 240e08c3d171
Revises: bbacc9ac9cbf
Create Date: 2024-12-24 15:10:19.693683

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '240e08c3d171'
down_revision = 'bbacc9ac9cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'updated_at')
    # ### end Alembic commands ###
