"""autogenerated_migration

Revision ID: a81511b92773
Revises: 57a471e7e0fb
Create Date: 2024-12-22 16:17:57.542590

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a81511b92773'
down_revision = '57a471e7e0fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('modified_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'modified_time')
    # ### end Alembic commands ###
