"""autogenerated_migration

Revision ID: 91e9e4e85298
Revises: 
Create Date: 2024-11-03 11:44:10.777253

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '91e9e4e85298'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'taken', 'cancelled', 'done', name='orderstatus'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_created_at'), 'order', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_executor_id'), 'order', ['executor_id'], unique=False)
    op.create_index(op.f('ix_order_order_id'), 'order', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_executor_id'), table_name='order')
    op.drop_index(op.f('ix_order_created_at'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
