"""autogenerated_migration

Revision ID: new_revision_id
Revises: 91e9e4e85298
Create Date: 2024-11-07

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import uuid


# revision identifiers, used by Alembic.
revision = 'new_revision_id'
down_revision = '91e9e4e85298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
        sa.Column('assigned_order_id', sa.UUID(), primary_key=True, default=uuid.uuid4),
        sa.Column('order_id', sa.UUID(), nullable=False, default=uuid.uuid4),
        sa.Column('status', sa.Enum('active', 'taken', 'cancelled', 'done', name='orderstatus'), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('executor_id', sa.Integer(), nullable=True),
        sa.Column('zone', sa.String(), nullable=False),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('taken_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('assigned_order_id')
    )
    op.create_index(op.f('ix_order_created_at'), 'order', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_executor_id'), 'order', ['executor_id'], unique=False)
    op.create_index(op.f('ix_order_order_id'), 'order', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_executor_id'), table_name='order')
    op.drop_index(op.f('ix_order_created_at'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
