"""autogenerated_migration

Revision ID: new_revision_id
Revises: 91e9e4e85298
Create Date: 2024-11-07

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import uuid


# revision identifiers, used by Alembic.
revision = 'new_revision_id'
down_revision = '91e9e4e85298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('assigned_order_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('executer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'taken', 'cancelled', 'done', name='orderstatus'), nullable=False),
    sa.Column('coin_coeff', sa.Float(), nullable=False),
    sa.Column('coin_bonus_amount', sa.Float(), nullable=False),
    sa.Column('final_coin_amount', sa.Float(), nullable=False),
    sa.Column('route_information', sa.String(), nullable=False),
    sa.Column('assign_time', sa.DateTime(), nullable=False),
    sa.Column('acquire_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('assigned_order_id')
    )
    op.create_index(op.f('ix_order_executer_id'), 'order', ['executer_id'], unique=False)
    op.create_index(op.f('ix_order_order_id'), 'order', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_executer_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
