apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: corag22035/design-system-7:backend_image
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-config
        # - secretRef:
        #     name: backend-secrets
        volumeMounts:
        - name: config-volume
          mountPath: /app/config  # Updated mountPath to be absolute
      volumes:
      - name: config-volume
        configMap:
          name: backend-config